version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - run: npm i && npm test
  deploy:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - run: npm i && npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: 's3://tecemergente-cicd'
workflows:
  test_and_build:
    jobs:
      - test
      - deploy
