version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - node/install:
          node-version: '17.8.0'
      - run: npm i && npm test
workflows:
  test_and_build:
    jobs:
      - test
